"""fix published_date type

Revision ID: 4865b5bdfd5e
Revises: 100753e6ce33
Create Date: 2026-06-29 15:28:42.767432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "4865b5bdfd5e"
down_revision: Union[str, Sequence[str], None] = "100753e6ce33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "published_date",
        type_=sa.Date(),
        postgresql_using="published_date::date",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "published_date",
        existing_type=sa.Date(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
